import sympy
from pyeuclid.formalization.relation import *

pi = sympy.pi


relations = [(Length(Point('P'),Point('Q')) - sympy.simplify('11.1000000000000')), (Angle(Point('N'),Point('Q'),Point('P')) - sympy.simplify('83/180*pi')), (Length(Point('P'),Point('R')) - sympy.simplify('20')), (Length(Point('M'),Point('N')) - ((sympy.simplify('3') * Variable('x')) - sympy.simplify('4'))), (Length(Point('N'),Point('P')) - ((sympy.simplify('2') * Variable('y')) + sympy.simplify('5'))), (Length(Point('N'),Point('Q')) - sympy.simplify('15.4000000000000')), (Angle(Point('M'),Point('N'),Point('Q')) - sympy.simplify('33/180*pi')), (Length(Point('M'),Point('N')) - ((sympy.simplify('3') * Variable('x')) - sympy.simplify('4'))), (Length(Point('Q'),Point('R')) - ((sympy.simplify('3') * Variable('z')) - sympy.simplify('3'))), (Angle(Point('M'),Point('R'),Point('Q')) - sympy.simplify('38/180*pi')), (Length(Point('M'),Point('R')) - sympy.simplify('17.9000000000000')), Between(Point('Q'),Point('N'),Point('R')), Collinear(Point('N'),Point('Q'),Point('R')), Between(Point('Q'),Point('M'),Point('P')), Collinear(Point('M'),Point('P'),Point('Q')), Parallelogram(Point('M'),Point('N'),Point('P'),Point('R')), Parallelogram(Point('M'),Point('N'),Point('P'),Point('R'))]
goal = Angle(Point('M'),Point('N'),Point('P'))
solution = '(71)/180*pi'

diagrammatic_relations = {SameSide(Point('N'),Point('P'),Point('M'),Point('R')), OppositeSide(Point('M'),Point('P'),Point('Q'),Point('R')), SameSide(Point('M'),Point('Q'),Point('N'),Point('P')), Between(Point('Q'),Point('M'),Point('P')), SameSide(Point('M'),Point('R'),Point('N'),Point('P')), SameSide(Point('N'),Point('Q'),Point('M'),Point('R')), SameSide(Point('M'),Point('Q'),Point('P'),Point('R')), SameSide(Point('P'),Point('Q'),Point('M'),Point('R')), NotCollinear(Point('M'),Point('N'),Point('R')), SameSide(Point('N'),Point('Q'),Point('P'),Point('R')), SameSide(Point('Q'),Point('R'),Point('M'),Point('N')), NotCollinear(Point('P'),Point('Q'),Point('R')), NotCollinear(Point('M'),Point('N'),Point('Q')), SameSide(Point('P'),Point('Q'),Point('M'),Point('N')), NotCollinear(Point('N'),Point('P'),Point('Q')), SameSide(Point('P'),Point('R'),Point('M'),Point('N')), OppositeSide(Point('N'),Point('R'),Point('M'),Point('P')), SameSide(Point('Q'),Point('R'),Point('N'),Point('P')), OppositeSide(Point('N'),Point('R'),Point('P'),Point('Q')), NotCollinear(Point('M'),Point('Q'),Point('R')), OppositeSide(Point('M'),Point('P'),Point('N'),Point('Q')), OppositeSide(Point('N'),Point('R'),Point('M'),Point('Q')), NotCollinear(Point('N'),Point('P'),Point('R')), NotCollinear(Point('M'),Point('N'),Point('P')), NotCollinear(Point('M'),Point('P'),Point('R')), SameSide(Point('M'),Point('N'),Point('P'),Point('R')), OppositeSide(Point('M'),Point('P'),Point('N'),Point('R'))}
