import sympy
from pyeuclid.formalization.relation import *

pi = sympy.pi


relations = [(Angle(Point('A'),Point('Y'),Point('Z'))-Angle(Point('Y'),Point('Z'),Point('X'))), (Angle(Point('B'),Point('Y'),Point('X')) - Variable('angle_1')), (Angle(Point('X'),Point('Y'),Point('Z')) - Variable('angle_2')), (Angle(Point('A'),Point('Y'),Point('Z')) - Variable('angle_3')), Between(Point('Y'),Point('A'),Point('B')), Collinear(Point('A'),Point('B'),Point('Y')), Parallel(Point('A'),Point('B'),Point('X'),Point('Z'))]
goal = Parallel(Point('B'),Point('A'),Point('X'),Point('Z'))
solution = True

diagrammatic_relations = {OppositeSide(Point('A'),Point('X'),Point('B'),Point('Z')), SameSide(Point('A'),Point('Z'),Point('X'),Point('Y')), SameSide(Point('A'),Point('Y'),Point('B'),Point('Z')), SameSide(Point('B'),Point('Y'),Point('X'),Point('Z')), NotCollinear(Point('A'),Point('X'),Point('Y')), SameSide(Point('Y'),Point('Z'),Point('B'),Point('X')), SameSide(Point('B'),Point('Y'),Point('A'),Point('X')), SameSide(Point('X'),Point('Z'),Point('B'),Point('Y')), SameSide(Point('A'),Point('B'),Point('X'),Point('Z')), SameSide(Point('A'),Point('Z'),Point('B'),Point('X')), NotCollinear(Point('A'),Point('Y'),Point('Z')), OppositeSide(Point('B'),Point('Z'),Point('A'),Point('X')), SameSide(Point('B'),Point('X'),Point('Y'),Point('Z')), SameSide(Point('X'),Point('Y'),Point('A'),Point('Z')), NotCollinear(Point('X'),Point('Y'),Point('Z')), NotCollinear(Point('B'),Point('X'),Point('Y')), SameSide(Point('B'),Point('X'),Point('A'),Point('Z')), NotCollinear(Point('A'),Point('B'),Point('Z')), NotCollinear(Point('B'),Point('Y'),Point('Z')), OppositeSide(Point('A'),Point('X'),Point('Y'),Point('Z')), SameSide(Point('A'),Point('Y'),Point('B'),Point('X')), SameSide(Point('X'),Point('Z'),Point('A'),Point('Y')), OppositeSide(Point('X'),Point('Y'),Point('B'),Point('Z')), OppositeSide(Point('Y'),Point('Z'),Point('A'),Point('X')), NotCollinear(Point('B'),Point('X'),Point('Z')), OppositeSide(Point('B'),Point('Z'),Point('X'),Point('Y')), SameSide(Point('A'),Point('Y'),Point('X'),Point('Z')), SameSide(Point('B'),Point('Y'),Point('A'),Point('Z')), NotCollinear(Point('A'),Point('X'),Point('Z')), OppositeSide(Point('A'),Point('B'),Point('Y'),Point('Z')), SameSide(Point('X'),Point('Z'),Point('A'),Point('B')), NotCollinear(Point('A'),Point('B'),Point('X')), OppositeSide(Point('A'),Point('B'),Point('X'),Point('Y'))}
