import sympy
from pyeuclid.formalization.relation import *

pi = sympy.pi


relations = [(Angle(Point('A'),Point('B'),Point('C')) - ((((sympy.simplify('3') * Variable('y')) + sympy.simplify('4')) / sympy.simplify('180')) * sympy.simplify('pi'))), (Angle(Point('B'),Point('A'),Point('D')) - sympy.simplify('58/180*pi')), (Angle(Point('A'),Point('D'),Point('C')) - ((((sympy.simplify('2') * Variable('y')) + sympy.simplify('16')) / sympy.simplify('180')) * sympy.simplify('pi'))), (Angle(Point('B'),Point('C'),Point('D')) - (((sympy.simplify('2') * Variable('x')) / sympy.simplify('180')) * sympy.simplify('pi'))), (Length(Point('C'),Point('O')) - Variable('radius_O')), (Length(Point('B'),Point('O')) - Variable('radius_O')), (Length(Point('D'),Point('O')) - Variable('radius_O')), (Length(Point('A'),Point('O')) - Variable('radius_O'))]
goal = Angle(Point('A'),Point('D'),Point('C'))
solution = '(80)/180*pi'

diagrammatic_relations = {SameSide(Point('B'),Point('O'),Point('A'),Point('C')), SameSide(Point('A'),Point('O'),Point('B'),Point('C')), SameSide(Point('B'),Point('C'),Point('D'),Point('O')), NotCollinear(Point('C'),Point('D'),Point('O')), SameSide(Point('C'),Point('D'),Point('A'),Point('B')), OppositeSide(Point('A'),Point('B'),Point('D'),Point('O')), SameSide(Point('C'),Point('D'),Point('B'),Point('O')), SameSide(Point('B'),Point('O'),Point('A'),Point('D')), SameSide(Point('B'),Point('O'),Point('C'),Point('D')), SameSide(Point('C'),Point('O'),Point('A'),Point('B')), SameSide(Point('C'),Point('D'),Point('A'),Point('O')), OppositeSide(Point('B'),Point('D'),Point('A'),Point('O')), NotCollinear(Point('A'),Point('B'),Point('O')), OppositeSide(Point('D'),Point('O'),Point('A'),Point('C')), NotCollinear(Point('B'),Point('D'),Point('O')), SameSide(Point('C'),Point('O'),Point('A'),Point('D')), SameSide(Point('A'),Point('B'),Point('C'),Point('D')), SameSide(Point('D'),Point('O'),Point('B'),Point('C')), SameSide(Point('A'),Point('D'),Point('B'),Point('C')), SameSide(Point('A'),Point('D'),Point('C'),Point('O')), OppositeSide(Point('A'),Point('C'),Point('D'),Point('O')), SameSide(Point('A'),Point('O'),Point('B'),Point('D')), NotCollinear(Point('A'),Point('D'),Point('O')), OppositeSide(Point('A'),Point('D'),Point('B'),Point('O')), OppositeSide(Point('B'),Point('C'),Point('A'),Point('O')), OppositeSide(Point('B'),Point('D'),Point('A'),Point('C')), NotCollinear(Point('A'),Point('B'),Point('D')), OppositeSide(Point('A'),Point('C'),Point('B'),Point('D')), SameSide(Point('A'),Point('O'),Point('C'),Point('D')), OppositeSide(Point('C'),Point('O'),Point('B'),Point('D')), OppositeSide(Point('A'),Point('B'),Point('C'),Point('O')), SameSide(Point('B'),Point('C'),Point('A'),Point('D')), NotCollinear(Point('B'),Point('C'),Point('O')), NotCollinear(Point('A'),Point('C'),Point('D')), SameSide(Point('D'),Point('O'),Point('A'),Point('B')), NotCollinear(Point('A'),Point('B'),Point('C')), OppositeSide(Point('A'),Point('C'),Point('B'),Point('O')), NotCollinear(Point('B'),Point('C'),Point('D')), NotCollinear(Point('A'),Point('C'),Point('O')), OppositeSide(Point('B'),Point('D'),Point('C'),Point('O'))}
