import sympy
from pyeuclid.formalization.relation import *

pi = sympy.pi


relations = [(Angle(Point('W'),Point('A'),Point('X')) - Variable('angle_11')), (Angle(Point('A'),Point('W'),Point('Y')) - Variable('angle_7')), (Angle(Point('A'),Point('Y'),Point('W')) - Variable('angle_6')), (Angle(Point('X'),Point('W'),Point('Z')) - Variable('angle_8')), (Angle(Point('X'),Point('A'),Point('Z')) - Variable('angle_10')), (Angle(Point('W'),Point('A'),Point('Y')) - Variable('angle_9')), (Angle(Point('W'),Point('Z'),Point('X')) - Variable('angle_3')), (Angle(Point('A'),Point('X'),Point('W')) - Variable('angle_1')), (Angle(Point('X'),Point('Y'),Point('Z')) - Variable('angle_5')), (Angle(Point('A'),Point('Z'),Point('Y')) - Variable('angle_4')), (Angle(Point('Y'),Point('A'),Point('Z')) - Variable('angle_12')), (Angle(Point('Y'),Point('X'),Point('Z')) - Variable('angle_2')), Between(Point('A'),Point('W'),Point('Z')), Collinear(Point('A'),Point('W'),Point('Z')), Between(Point('A'),Point('X'),Point('Y')), Collinear(Point('A'),Point('X'),Point('Y')), Perpendicular(Point('W'),Point('Y'),Point('Y'),Point('Z')), Rectangle(Point('W'),Point('X'),Point('Z'),Point('Y')), (Variable('angle_1') - sympy.simplify('30/180*pi')), Rectangle(Point('W'),Point('X'),Point('Z'),Point('Y')), (Variable('angle_1') - sympy.simplify('30/180*pi'))]
goal = Variable('angle_6')
solution = '(60)/180*pi'

diagrammatic_relations = {OppositeSide(Point('W'),Point('Z'),Point('X'),Point('Y')), SameSide(Point('Y'),Point('Z'),Point('W'),Point('X')), SameSide(Point('W'),Point('X'),Point('Y'),Point('Z')), SameSide(Point('W'),Point('Y'),Point('X'),Point('Z')), NotCollinear(Point('A'),Point('Y'),Point('Z')), OppositeSide(Point('W'),Point('Z'),Point('A'),Point('Y')), NotCollinear(Point('X'),Point('Y'),Point('Z')), NotCollinear(Point('A'),Point('W'),Point('Y')), SameSide(Point('A'),Point('Y'),Point('X'),Point('Z')), SameSide(Point('X'),Point('Z'),Point('W'),Point('Y')), SameSide(Point('A'),Point('X'),Point('Y'),Point('Z')), NotCollinear(Point('W'),Point('X'),Point('Y')), OppositeSide(Point('W'),Point('Z'),Point('A'),Point('X')), OppositeSide(Point('X'),Point('Y'),Point('A'),Point('Z')), NotCollinear(Point('A'),Point('X'),Point('Z')), OppositeSide(Point('X'),Point('Y'),Point('W'),Point('Z')), NotCollinear(Point('A'),Point('W'),Point('X')), SameSide(Point('A'),Point('Z'),Point('W'),Point('X')), NotCollinear(Point('W'),Point('Y'),Point('Z')), SameSide(Point('A'),Point('Z'),Point('W'),Point('Y')), SameSide(Point('A'),Point('X'),Point('W'),Point('Y')), NotCollinear(Point('W'),Point('X'),Point('Z')), SameSide(Point('A'),Point('Y'),Point('W'),Point('X')), SameSide(Point('A'),Point('W'),Point('X'),Point('Z')), OppositeSide(Point('X'),Point('Y'),Point('A'),Point('W')), SameSide(Point('A'),Point('W'),Point('Y'),Point('Z'))}
