import sympy
from pyeuclid.formalization.relation import *

pi = sympy.pi


relations = [(Length(Point('B'),Point('C')) - (Variable('x') + sympy.simplify('10'))), (Length(Point('B'),Point('E')) - Variable('x')), Between(Point('E'),Point('A'),Point('D')), Collinear(Point('A'),Point('D'),Point('E')), Perpendicular(Point('B'),Point('E'),Point('D'),Point('E')), (Area(Point('A'),Point('B'),Point('C'),Point('D')) - sympy.simplify('2000')), Parallelogram(Point('A'),Point('B'),Point('C'),Point('D'))]
goal = Variable('x')
solution = '40'

diagrammatic_relations = {SameSide(Point('C'),Point('D'),Point('B'),Point('E')), NotCollinear(Point('A'),Point('B'),Point('E')), OppositeSide(Point('A'),Point('C'),Point('B'),Point('E')), SameSide(Point('C'),Point('D'),Point('A'),Point('B')), SameSide(Point('A'),Point('E'),Point('C'),Point('D')), SameSide(Point('B'),Point('C'),Point('A'),Point('E')), SameSide(Point('A'),Point('B'),Point('C'),Point('D')), SameSide(Point('D'),Point('E'),Point('A'),Point('B')), SameSide(Point('A'),Point('D'),Point('B'),Point('C')), SameSide(Point('C'),Point('E'),Point('A'),Point('B')), NotCollinear(Point('A'),Point('C'),Point('E')), OppositeSide(Point('A'),Point('D'),Point('B'),Point('E')), OppositeSide(Point('A'),Point('D'),Point('C'),Point('E')), SameSide(Point('B'),Point('E'),Point('C'),Point('D')), SameSide(Point('A'),Point('E'),Point('B'),Point('C')), SameSide(Point('B'),Point('C'),Point('D'),Point('E')), OppositeSide(Point('B'),Point('D'),Point('A'),Point('C')), SameSide(Point('D'),Point('E'),Point('B'),Point('C')), SameSide(Point('A'),Point('B'),Point('C'),Point('E')), SameSide(Point('A'),Point('E'),Point('B'),Point('D')), NotCollinear(Point('A'),Point('B'),Point('D')), OppositeSide(Point('A'),Point('C'),Point('B'),Point('D')), Between(Point('E'),Point('A'),Point('D')), NotCollinear(Point('B'),Point('C'),Point('E')), OppositeSide(Point('C'),Point('E'),Point('B'),Point('D')), NotCollinear(Point('C'),Point('D'),Point('E')), SameSide(Point('B'),Point('C'),Point('A'),Point('D')), OppositeSide(Point('B'),Point('E'),Point('A'),Point('C')), SameSide(Point('D'),Point('E'),Point('A'),Point('C')), NotCollinear(Point('A'),Point('C'),Point('D')), OppositeSide(Point('B'),Point('D'),Point('C'),Point('E')), NotCollinear(Point('A'),Point('B'),Point('C')), NotCollinear(Point('B'),Point('D'),Point('E')), NotCollinear(Point('B'),Point('C'),Point('D'))}
