import sympy
from pyeuclid.formalization.relation import *

pi = sympy.pi


relations = [(Angle(Point('R'),Point('P'),Point('S')) - sympy.simplify('130/180*pi')), (Angle(Point('Q'),Point('P'),Point('T')) - sympy.simplify('112/180*pi')), Between(Point('P'),Point('R'),Point('T')), Collinear(Point('P'),Point('R'),Point('T')), (Length(Point('P'),Point('S')) - 2), (Length(Point('P'),Point('T')) - 2), (Length(Point('P'),Point('R')) - 2), (Length(Point('P'),Point('Q')) - 2)]
goal = (Angle(Point('R'),Point('P'),Point('S')) * 2)
solution = '4.54'

diagrammatic_relations = {SameSide(Point('Q'),Point('R'),Point('S'),Point('T')), SameSide(Point('P'),Point('Q'),Point('R'),Point('S')), OppositeSide(Point('R'),Point('T'),Point('Q'),Point('S')), OppositeSide(Point('Q'),Point('S'),Point('P'),Point('R')), OppositeSide(Point('R'),Point('T'),Point('P'),Point('S')), NotCollinear(Point('P'),Point('S'),Point('T')), SameSide(Point('P'),Point('S'),Point('Q'),Point('T')), NotCollinear(Point('P'),Point('R'),Point('S')), OppositeSide(Point('Q'),Point('R'),Point('P'),Point('S')), NotCollinear(Point('Q'),Point('R'),Point('S')), OppositeSide(Point('R'),Point('T'),Point('P'),Point('Q')), SameSide(Point('S'),Point('T'),Point('Q'),Point('R')), OppositeSide(Point('R'),Point('S'),Point('P'),Point('Q')), SameSide(Point('P'),Point('R'),Point('Q'),Point('S')), SameSide(Point('S'),Point('T'),Point('P'),Point('Q')), NotCollinear(Point('R'),Point('S'),Point('T')), NotCollinear(Point('P'),Point('Q'),Point('S')), NotCollinear(Point('P'),Point('Q'),Point('T')), NotCollinear(Point('P'),Point('Q'),Point('R')), OppositeSide(Point('Q'),Point('S'),Point('P'),Point('T')), SameSide(Point('P'),Point('R'),Point('S'),Point('T')), SameSide(Point('P'),Point('Q'),Point('S'),Point('T')), SameSide(Point('R'),Point('S'),Point('Q'),Point('T')), SameSide(Point('P'),Point('S'),Point('Q'),Point('R')), NotCollinear(Point('Q'),Point('S'),Point('T')), SameSide(Point('P'),Point('R'),Point('Q'),Point('T')), NotCollinear(Point('Q'),Point('R'),Point('T')), SameSide(Point('Q'),Point('T'),Point('R'),Point('S')), SameSide(Point('Q'),Point('T'),Point('P'),Point('S')), OppositeSide(Point('Q'),Point('S'),Point('R'),Point('T')), SameSide(Point('P'),Point('T'),Point('R'),Point('S')), OppositeSide(Point('P'),Point('T'),Point('Q'),Point('S')), SameSide(Point('P'),Point('T'),Point('Q'),Point('R'))}
