import sympy
from pyeuclid.formalization.relation import *

pi = sympy.pi


relations = [(Length(Point('A'),Point('C')) - sympy.simplify('4')),(Length(Point('A'),Point('B')) - sympy.simplify('6')), (Length(Point('B'),Point('C')) - sympy.simplify('4')), (Length(Point('A'),Point('D')) - sympy.simplify('5')), (Length(Point('D'),Point('E')) - sympy.simplify('6')), Perpendicular(Point('A'),Point('D'),Point('D'),Point('E')), Perpendicular(Point('B'),Point('E'),Point('D'),Point('E')), Perpendicular(Point('A'),Point('B'),Point('B'),Point('E')),Rectangle(Point('A'),Point('B'),Point('E'),Point('D'))]
goal = Area(Point('B'),Point('E'),Point('D'),Point('A'))-Area(Point('A'),Point('B'),Point('C'))
solution = '22.1'

diagrammatic_relations = {SameSide(Point('A'),Point('C'),Point('D'),Point('E')), OppositeSide(Point('B'),Point('D'),Point('A'),Point('C')), SameSide(Point('A'),Point('C'),Point('B'),Point('E')), SameSide(Point('C'),Point('D'),Point('A'),Point('B')), OppositeSide(Point('B'),Point('E'),Point('C'),Point('D')), NotCollinear(Point('A'),Point('D'),Point('E')), NotCollinear(Point('B'),Point('C'),Point('E')), SameSide(Point('A'),Point('B'),Point('C'),Point('D')), OppositeSide(Point('D'),Point('E'),Point('A'),Point('C')), NotCollinear(Point('A'),Point('C'),Point('D')), OppositeSide(Point('A'),Point('E'),Point('B'),Point('C')), SameSide(Point('B'),Point('C'),Point('A'),Point('D')), SameSide(Point('A'),Point('D'),Point('B'),Point('C')), SameSide(Point('B'),Point('C'),Point('D'),Point('E')), NotCollinear(Point('B'),Point('C'),Point('D')), SameSide(Point('C'),Point('E'),Point('B'),Point('D')), NotCollinear(Point('A'),Point('B'),Point('C')), SameSide(Point('B'),Point('E'),Point('A'),Point('D')), NotCollinear(Point('C'),Point('D'),Point('E')), SameSide(Point('A'),Point('B'),Point('D'),Point('E')), SameSide(Point('C'),Point('E'),Point('A'),Point('B')), OppositeSide(Point('A'),Point('E'),Point('B'),Point('D')), OppositeSide(Point('B'),Point('D'),Point('A'),Point('E')), NotCollinear(Point('A'),Point('B'),Point('D')), NotCollinear(Point('B'),Point('D'),Point('E')), OppositeSide(Point('A'),Point('C'),Point('B'),Point('D')), OppositeSide(Point('B'),Point('C'),Point('A'),Point('E')), SameSide(Point('B'),Point('E'),Point('A'),Point('C')), SameSide(Point('D'),Point('E'),Point('A'),Point('B')), NotCollinear(Point('A'),Point('B'),Point('E')), OppositeSide(Point('B'),Point('D'),Point('C'),Point('E')), OppositeSide(Point('A'),Point('E'),Point('C'),Point('D')), SameSide(Point('A'),Point('D'),Point('B'),Point('E')), SameSide(Point('C'),Point('D'),Point('B'),Point('E')), OppositeSide(Point('A'),Point('D'),Point('C'),Point('E')), SameSide(Point('C'),Point('E'),Point('A'),Point('D')), SameSide(Point('C'),Point('D'),Point('A'),Point('E')), NotCollinear(Point('A'),Point('C'),Point('E')), OppositeSide(Point('D'),Point('E'),Point('B'),Point('C')), SameSide(Point('A'),Point('B'),Point('C'),Point('E'))}
