import os
import json
from pathlib import Path
import shutil
from PIL import Image
from openai import OpenAI
from pyeuclid.informalization.gpt import GPT_Model

def create_problem_prompt(problem, goal):
    full_prompt = f"""
Here is a geometry problem constructed by a neural symbolic solver:
{problem}
The goal is to prove that:
{goal}
Please rephrase and describe the problem and goal using natural language.
"""
    return full_prompt

def create_proof_prompt(problem, goal, proof):
    full_prompt = f"""
Here is a geometry problem constructed by a neural symbolic solver:
{problem}
The goal is to prove that:
{goal}
The following is a correct proof generated by a neural symbolic solver:
{proof}
Please reason step by step, rephrasing the above proof to generate a plain text natural language proof **without step indices**.
"""
    return full_prompt


client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENAI_API_KEY"),
)
model = GPT_Model(client=client, patience=1, max_tokens=4096)

dataset_dir = "informalized_dataset"
dst_dataset_dir = "refined_dataset"
data_json_list = []
image_file_list = []
for entry in Path(dataset_dir).rglob("*data.json"):
    sample_dir = entry.parent
    data_json_list.append(os.path.join(sample_dir, "data.json"))
    image_file_list.append(os.path.join(sample_dir, "diagram.jpg"))
print("begin")

# data_json_list = ["informalized_dataset/rank_5/problem_48/sample_0/data.json"]
# image_file_list = ["informalized_dataset/rank_5/problem_48/sample_0/diagram.jpg"]
total_num = len(data_json_list)
error_list = list()
result = dict()

total_problem_prompt_tokens = 0
total_problem_completion_tokens = 0
total_proof_prompt_tokens = 0
total_proof_completion_tokens = 0
num_samples = 100

for idx, (data_json, image_file) in enumerate(zip(data_json_list, image_file_list)):
    print(f"{idx + 1}/{total_num}")
    if idx >= num_samples: break
    try:
        with open(data_json, "r") as f:
            data = json.load(f)
    except:
        error_list.append(data_json)
        continue
    problem = data["problem"]
    goal = data["goal"]
    proof = data["proof"]
    informal_problem = data["informal_problem"]
    informal_goal = data["informal_goal"]
    informal_proof = data["informal_proof"]

    # template_problem_tokens = model.count_token(informal_problem)
    # data["template_problem_tokens"] = template_problem_tokens
    # print(template_problem_tokens)

    # template_goal_tokens = model.count_token(informal_goal)
    # data["template_goal_tokens"] = template_goal_tokens
    # print(template_goal_tokens)

    # template_proof_tokens = model.count_token(informal_proof)
    # data["template_proof_tokens"] = template_proof_tokens
    # print(template_proof_tokens)
    # exit()
    
    prompt = create_problem_prompt(informal_problem, informal_goal)
    print(prompt)
    refined_problem, usage = model.get_response(user_prompt=prompt, decoded_image=None)
    data["refined_problem"] = refined_problem
    print(refined_problem)
    data["problem_prompt_tokens"] = usage.prompt_tokens
    data["problem_completion_tokens"] = usage.completion_tokens
    print(usage.prompt_tokens, usage.completion_tokens)

    total_problem_prompt_tokens += usage.prompt_tokens
    total_problem_completion_tokens += usage.completion_tokens

    prompt = create_proof_prompt(informal_problem, informal_goal, informal_proof)
    print(prompt)
    refined_proof, usage = model.get_response(user_prompt=prompt, decoded_image=None)
    data["refined_proof"] = refined_proof
    print(refined_proof)
    data["proof_prompt_tokens"] = usage.prompt_tokens
    data["proof_completion_tokens"] = usage.completion_tokens
    print(usage.prompt_tokens, usage.completion_tokens)

    total_proof_prompt_tokens += usage.prompt_tokens
    total_proof_completion_tokens += usage.completion_tokens

    dst_data_json = data_json.replace(dataset_dir, dst_dataset_dir)
    dst_image_file = image_file.replace(dataset_dir, dst_dataset_dir)
    os.makedirs(os.path.dirname(dst_data_json), exist_ok=True)
    with open(dst_data_json, "w") as f:
        json.dump(data, f, indent=4)
    # if os.path.islink(dst_image_file):
    #     os.unlink(dst_image_file)
    # elif os.path.exists(dst_image_file):
    #     os.remove(dst_image_file)
    # os.symlink(os.path.abspath(image_file), dst_image_file)

    # exit()

print(error_list)
print(f"avg_problem_prompt_tokens: {total_problem_prompt_tokens / num_samples}")
print(f"avg_problem_completion_tokens: {total_problem_completion_tokens / num_samples}")
print(f"avg_proof_prompt_tokens: {total_proof_prompt_tokens / num_samples}")
print(f"avg_proof_completion_tokens: {total_proof_completion_tokens / num_samples}")