import os
import json
from pathlib import Path
import shutil
from PIL import Image
from openai import OpenAI
from pyeuclid.informalization.llm import OpenAIProvider

def create_problem_prompt(problem, goal):
    full_prompt = f"""
Here is a geometry problem constructed by a neural symbolic solver:
{problem}
The goal is to calculate the value of:
{goal}
Please rephrase and describe the problem and goal using natural language.
"""
    return full_prompt

def create_proof_prompt(problem, proof):
    full_prompt = f"""
Here is a geometry problem constructed by a neural symbolic solver:
{problem}
The following is a correct solution generated by a neural symbolic solver:
{proof}
Please fully understand the steps. And generate a **correct and concise** natural language solution in plain text without any step numbers. Starting your final solution with FINAL_SOLUTION:
"""
    return full_prompt


client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENAI_API_KEY"),
)
model = OpenAIProvider(client=client)

dataset_dir = "task1_template"
dst_dataset_dir = "task1_llm"
data_json_list = []
image_file_list = []
for entry in Path(dataset_dir).rglob("*data.json"):
    sample_dir = entry.parent
    data_json_list.append(os.path.join(sample_dir, "data.json"))
    image_file_list.append(os.path.join(sample_dir, "diagram.pdf"))
print("begin")

total_num = len(data_json_list)
error_list = list()
result = dict()

for idx, (data_json, image_file) in enumerate(zip(data_json_list, image_file_list)):
    if idx != 7: continue
    print(f"{idx + 1}/{total_num}")
    try:
        with open(data_json, "r") as f:
            data = json.load(f)
    except:
        error_list.append(data_json)
        continue
    problem = data["problem"]
    goal = data["goal"]
    proof = data["proof"]
    informal_problem = data["informal_problem"]
    informal_goal = data["informal_goal"]
    informal_proof = data["informal_proof"]
    
    prompt = create_problem_prompt(informal_problem, informal_goal)
    print(prompt)
    refined_problem = model.generate(user_prompt=prompt)
    data["refined_problem"] = refined_problem
    print(refined_problem)

    prompt = create_proof_prompt(refined_problem, informal_proof)
    print(prompt)
    while True:
        refined_proof = model.generate(user_prompt=prompt, image_path=image_file)
        if "FINAL_PROOF:" in refined_proof:
            refined_proof = refined_proof.split("FINAL_PROOF:")[-1]
            while refined_proof[0] == "\n":
                refined_proof = refined_proof[1:]
            break
    data["refined_proof"] = refined_proof
    print(refined_proof)

    dst_data_json = data_json.replace(dataset_dir, dst_dataset_dir)
    dst_image_file = image_file.replace(dataset_dir, dst_dataset_dir)
    os.makedirs(os.path.dirname(dst_data_json), exist_ok=True)
    with open(dst_data_json, "w") as f:
        json.dump(data, f, indent=4)
    if os.path.islink(dst_image_file):
        os.unlink(dst_image_file)
    elif os.path.exists(dst_image_file):
        os.remove(dst_image_file)
    os.symlink(os.path.abspath(image_file), dst_image_file)
    break

print(error_list)