import os
import json
from pathlib import Path
import shutil
from PIL import Image
from openai import OpenAI
from pyeuclid.informalization.llm import OpenAIProvider

def create_problem_prompt(problem, goal):
    full_prompt = f"""
Here is a geometry problem constructed by a neural symbolic solver:
{problem}
The goal is to prove that:
{goal}
Please rephrase and describe the problem and goal using natural language.
"""
    return full_prompt

def create_proof_prompt(problem, goal, proof):
    full_prompt = f"""
Here is a geometry problem constructed by a neural symbolic solver:
{problem}
The goal is to prove that:
{goal}
The following is a correct proof generated by a neural symbolic solver:
{proof}
Please read and fully understand the above proof. Now generate a **concise and correct** proof which follows the idea of the above proof and omit redundant steps.
"""
    return full_prompt


client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENAI_API_KEY"),
)
model = OpenAIProvider(client=client)

with open("data/informal_task2_samples.json", "r") as f:
    data_list = json.load(f)
# print(data_list)


for idx, data in enumerate(data_list):
    print(idx)
    problem = data["problem"]
    goal = data["goal"]
    proof = data["proof"]
    informal_problem = data["informal_problem"]
    informal_goal = data["informal_goal"]
    informal_proof = data["informal_proof"]
    
    prompt = create_problem_prompt(informal_problem, informal_goal)
    print(prompt)
    refined_problem = model.generate(user_prompt=prompt)
    data["refined_problem"] = refined_problem
    print(refined_problem)

    prompt = create_proof_prompt(informal_problem, informal_goal, informal_proof)
    print(prompt)
    refined_proof = model.generate(user_prompt=prompt)
    data["refined_proof"] = refined_proof
    print(refined_proof)

    if idx >= 0 : break

with open("data/refine_task2_samples.json", "w") as f:
    json.dump(data_list, f, indent=4)