import os
import json
from pathlib import Path
import shutil
from PIL import Image
from openai import OpenAI
from pyeuclid.informalization.gpt import GPT_Model


def create_proof_prompt(problem, goal, proof):
    full_prompt = f"""
    Here is a geometry problem:
    {problem}
    The goal is to proof:
    {goal}
    The following is a correct proof generated by a neural symbolic solver:
    {proof}
    Please reason step by step, rephrasing and extracting key steps in the above proof to generate a plain text natural language proof without step indices.
    """
    return full_prompt


client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENAI_API_KEY"),
)
model = GPT_Model(client=client, patience=1, max_tokens=4096)

dataset_dir = "informalized_dataset"
dst_dataset_dir = "refined_dataset"
# data_json_list = []
# image_file_list = []
# for entry in Path(dataset_dir).rglob("*data.json"):
#     sample_dir = entry.parent
#     data_json_list.append(os.path.join(sample_dir, "data.json"))
#     image_file_list.append(os.path.join(sample_dir, "diagram.jpg"))
# print("begin")

data_json_list = ["informalized_dataset/rank_5/problem_48/sample_0/data.json"]
image_file_list = ["informalized_dataset/rank_5/problem_48/sample_0/diagram.jpg"]
total_num = len(data_json_list)
error_list = list()
result = dict()

for idx, (data_json, image_file) in enumerate(zip(data_json_list, image_file_list)):
    print(f"{idx + 1}/{total_num}")
    try:
        with open(data_json, "r") as f:
            data = json.load(f)
    except:
        error_list.append(data_json)
        continue
    problem = data["problem"]
    goal = data["goal"]
    proof = data["proof"]
    informal_problem = data["informal_problem"]
    informal_goal = data["informal_goal"]
    informal_proof = data["informal_proof"]
    
    prompt = create_proof_prompt(informal_problem, informal_goal, informal_proof)
    print(prompt)
    refined_proof = model.get_response(user_prompt=prompt, decoded_image=Image.open(image_file))
    data["refined_proof"] = refined_proof
    print(refined_proof)

    dst_data_json = data_json.replace(dataset_dir, dst_dataset_dir)
    dst_image_file = image_file.replace(dataset_dir, dst_dataset_dir)
    os.makedirs(os.path.dirname(dst_data_json), exist_ok=True)
    with open(dst_data_json, "w") as f:
        json.dump(data, f, indent=4)
    if os.path.islink(dst_image_file):
        os.unlink(dst_image_file)
    elif os.path.exists(dst_image_file):
        os.remove(dst_image_file)
    os.symlink(os.path.abspath(image_file), dst_image_file)

    exit()

print(error_list)